version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Python deps 
          command: |
            sudo pip install -r requirements.txt 
            python flask_project/bakend/service/run.py
