version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install Python deps 
          command: |
            sudo cd /home/ec2-user/Project/Ledger_project/flask_project/backend/service
            sudo pip install .
            sudo pip install sqlalchemy
