version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
          environment:
            DATABASE_URL: postgres+psycopg2://postgres:password@database-1.ccxp9suofmqw.us-east-2.rds.amazonaws.com:5432
        - image: circleci/postgres:9.6.2
          environment: # environment variables for the Postgres container.
             POSTGRES_USER: postgres
             POSTGRES_DB: password
    steps:
      - checkout
      - run:
          name: Install Python deps
          command: |
            sudo pip install -r requirements.txt
            python flask_project/backend/service/run.py
